Web/MoiteRecepti.Web/Areas/Administration/Controllers/AdministrationController.cs
namespace MoiteRecepti.Web.Areas.Administration.Controllers
{
    using MoiteRecepti.Common;
    using MoiteRecepti.Web.Controllers;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class AdministrationController : BaseController
    {
    }
}

Web/MoiteRecepti.Web/Areas/Administration/Controllers/DashboardController.cs
namespace MoiteRecepti.Web.Areas.Administration.Controllers
{
    public class DashboardController : AdministrationController
    {
    }
}

Web/MoiteRecepti.Web/Controllers/BaseController.cs
namespace MoiteRecepti.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class BaseController : Controller
    {
    }
}

Web/MoiteRecepti.Web/Controllers/GatherRecipesController.cs
using Microsoft.AspNetCore.Mvc;
using MoiteRecepti.Services;
using System.Threading.Tasks;

namespace MoiteRecepti.Web.Controllers
{
    public class GatherRecipesController : BaseController
    {
        private readonly IGotvachBgScraperService gotvachBgScraperService;

        public GatherRecipesController(IGotvachBgScraperService gotvachBgScraperService)
        {
            this.gotvachBgScraperService = gotvachBgScraperService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        public async Task<IActionResult> Add()
        {
            await this.gotvachBgScraperService.ImportRecipesAsync(200, 201);

            return this.Redirect("/");
        }
    }
}

Web/MoiteRecepti.Web/Controllers/HomeController.cs
namespace MoiteRecepti.Web.Controllers
{
    using System.Diagnostics;
    using System.Linq;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using MoiteRecepti.Data;
    using MoiteRecepti.Data.Common.Repositories;
    using MoiteRecepti.Data.Models;
    using MoiteRecepti.Services.Data;
    using MoiteRecepti.Web.ViewModels;
    using MoiteRecepti.Web.ViewModels.Home;

    public class HomeController : BaseController
    {
        private readonly IGetCountsService countsService;

        public HomeController(IGetCountsService countsService)
        {
            this.countsService = countsService;
        }

        public IActionResult Index()
        {
            var countsDto = this.countsService.GetCounts();
            var viewModel = new IndexViewModel
            {
                CategoriesCount = countsDto.CategoriesCount,
                ImagesCount = countsDto.ImagesCount,
                IngredientsCount = countsDto.IngredientsCount,
                RecipesCount = countsDto.RecipesCount,
            };
            return this.View(viewModel);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Web/MoiteRecepti.Web/Controllers/RecipesController.cs
namespace MoiteRecepti.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.CodeAnalysis.Operations;
    using MoiteRecepti.Data.Models;
    using MoiteRecepti.Services.Data;
    using MoiteRecepti.Web.ViewModels;
    using MoiteRecepti.Web.ViewModels.Recipes;
    using System;
    using System.Security.Claims;
    using System.Threading.Tasks;

    public class RecipesController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly IRecipesService recipesService;
        private readonly UserManager<ApplicationUser> userManager;

        public RecipesController(
            ICategoriesService categoriesService,
            IRecipesService recipesService,
            UserManager<ApplicationUser> userManager)
        {
            this.categoriesService = categoriesService;
            this.recipesService = recipesService;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult Create()
        {
            var viewModel = new CreateRecipeInputModel();
            viewModel.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateRecipeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            //try
            //{
                await this.recipesService.CreateAsync(input, user.Id);
            //}
            //catch (Exception ex)
            //{
            //    this.ModelState.AddModelError(string.Empty, ex.Message);
            //}
            //TODO: Redirect to recipe info page
            return this.Redirect("/");
        }

        public IActionResult All(int id = 1)
        {
            const int ItemPerPage = 12;
            var viewModel = new RecipesListViewModel
            {
                ItemsPerPage = ItemPerPage,
                PageNumber = id,
                RecipesCount = this.recipesService.GetCount(),
                Recipes = this.recipesService.GetAll<RecipeInListViewModel>(id, 12),
            };
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var recipe = this.recipesService.GetById<SingleRecipeViewModel>(id);
            return this.View(recipe);
        }
    }
}

Web/MoiteRecepti.Web/Views/GatherRecipes/Index.cshtml
@using MoiteRecepti.Common
@model MoiteRecepti.Web.ViewModels.Home.IndexViewModel
@{
    this.ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <a class="button" asp-controller="GatherRecipes" asp-action="Add" >Add Data</a>
</div>

Web/MoiteRecepti.Web/Views/Home/Index.cshtml
@using MoiteRecepti.Common
@model MoiteRecepti.Web.ViewModels.Home.IndexViewModel
@{
    this.ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to What2Eat!</h1>
    
    <div class="col-md-4 offset-md-4">
    <ul class="list-group">
            <p>We have</p>
            <li class="list-group-item bg-accent">Recipes: @Model.RecipesCount</li>
            <li class="list-group-item bg-accent">Categories: @Model.CategoriesCount</li>
            <li class="list-group-item bg-accent">Images: @Model.ImagesCount</li>
            <li class="list-group-item bg-accent">Ingredients: @Model.IngredientsCount</li>
    </ul>
    </div>
</div>

Web/MoiteRecepti.Web/Views/Recipes/All.cshtml
@model RecipesListViewModel
@{
    this.ViewData["Title"] = $"All Recipes, Page {Model.PageNumber}";
}

<h1>@this.ViewData["Title"]</h1>
<hr />
<div class="row">
@foreach(var recipe in this.Model.Recipes)
{
    <div class="media col-md-3">
            <img src="@recipe.ImageUrl" class="mr-3 img-responsive"/>
        <div class="media-body">
                <h5 class="mt-0"><a asp-action="ById" asp-route-id="@recipe.Id">@recipe.Name</a></h5>
            @recipe.CategoryName
        </div>
    </div>
}
</div>

<hr />
<partial name="_PagingPartial" model="@Model"/>

Web/MoiteRecepti.Web/Views/Recipes/ById.cshtml
@model MoiteRecepti.Web.ViewModels.Recipes.SingleRecipeViewModel
@{
    this.ViewData["Title"] = Model.Name;
}

<div class="single-recipe-layout1">
    <div class="ctg-name">@Model.CategoryName</div>
    <h2 class="item-title">@this.ViewData["Title"]</h2>
    <div class="row mb-4">
        <div class="col-xl-9 col-12">
            <ul class="entry-meta">
                <li class="single-meta">
                    <i class="far fa-calendar-alt"></i>
                    @Model.CreatedOn.ToShortDateString()
                </li>
                <li class="single-meta">
                    <i class="fas fa-user"></i> by
                    @if (string.IsNullOrWhiteSpace(Model.AddedByUserEmail))
                    {
                        <a href="@Model.OriginalUrl" target="_blank">recepti.gotvach.bg</a>
                    }
                    else
                    {
                        <span>@Model.AddedByUserEmail</span>
                    }
                </li>
                <li class="single-meta">
                    <ul class="item-rating">
                        <li class="star-fill" data-vote="1"><i class="fas fa-star"></i></li>
                        <li class="star-fill" data-vote="2"><i class="fas fa-star"></i></li>
                        <li class="star-fill" data-vote="3"><i class="fas fa-star"></i></li>
                        <li class="star-fill" data-vote="4"><i class="fas fa-star"></i></li>
                        <li class="star-fill" data-vote="5"><i class="fas fa-star"></i></li>
                        @* <li><span id="averageVoteValue">@Model.AverageVote.ToString("0.0")</span><span> / 5</span> </li> *@
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <div class="item-figure">
        <img class="img-fluid w-100 h-25" src="@Model.ImageUrl" alt="@Model.Name" />
    </div>
    <div class="item-feature">
        <ul>
            <li>
                <div class="feature-wrap">
                    <div class="media">
                        <div class="feature-icon">
                            <i class="far fa-clock"></i>
                        </div>
                        <div class="media-body space-sm">
                            <div class="feature-title">PREP TIME</div>
                            <div class="feature-sub-title">@Model.PreparationTime.TotalMinutes Mins</div>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="feature-wrap">
                    <div class="media">
                        <div class="feature-icon">
                            <i class="fas fa-utensils"></i>
                        </div>
                        <div class="media-body space-sm">
                            <div class="feature-title">COOK TIME</div>
                            <div class="feature-sub-title">@Model.CookingTime.TotalMinutes Mins</div>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="feature-wrap">
                    <div class="media">
                        <div class="feature-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        <div class="media-body space-sm">
                            <div class="feature-title">SERVING</div>
                            <div class="feature-sub-title">
                                @Model.PortionsCount
                                @if (Model.PortionsCount == 1)
                                {
                                    <span>Person</span>
                                }
                                else
                                {
                                    <span>People</span>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="feature-wrap">
                    <div class="media">
                        <div class="feature-icon">
                            <i class="fa fa-list-ol"></i>
                        </div>
                        <div class="media-body space-sm">
                            <div class="feature-title">CATEGORY RECIPES</div>
                            <div class="feature-sub-title">@Model.CategoryRecipesCount</div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="making-elements-wrap">
        <div class="row">
            <div class="col-md-6">
                <p class="item-description">
                    @Model.Instructions
                </p>
            </div>
            <div class="col-md-6">
                <div class="ingridients-wrap">
                    <h3 class="item-title"><i class="fas fa-list-ul"></i>Ingridients</h3>
                    @foreach (var ingredient in Model.Ingredients)
                    {
                        <div class="checkbox checkbox-primary">
                            <label for="checkbox1">@ingredient.Quantity @ingredient.IngredientName</label>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<form method="post" id="antiForgeryForm"></form>
@* @section Scripts {
    <script>
        $("li[data-vote]").each(function (el) {
            $(this).click(function () {
                var value = $(this).attr("data-vote");
                var recipeId = @Model.Id;
                var antiForgeryToken = $('#antiForgeryForm input[name=__RequestVerificationToken]').val();
                var data = { recipeId: recipeId, value: value };
                $.ajax({
                    type: "POST",
                    url: "/api/Votes",
                    data: JSON.stringify(data),
                    headers: {
                        'X-CSRF-TOKEN': antiForgeryToken
                    },
                    success: function (data) {
                        $('#averageVoteValue').html(data.averageVote.toFixed(1));
                    },
                    contentType: 'application/json',
                });
            })
        });
    </script> *@

Web/MoiteRecepti.Web/Views/Recipes/Create.cshtml
@using MoiteRecepti.Web.ViewModels.Recipes
@model CreateRecipeInputModel
@{
    this.ViewData["Title"] = "Add new recipe";
    var categoryItems = this.Model.CategoriesItems.Select(x => new SelectListItem(x.Value, x.Key));
}


<form method="post" class="col-md-6 offset-md-3" enctype="multipart/form-data">
    <h1>Add new recipe</h1>
    <div asp-validation-summary="All"></div>
    <div class="form-group">
    <label asp-for="Name"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Instructions"></label>
        <textarea asp-for="Instructions" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Instructions" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CookingTime"></label>
        <input asp-for="CookingTime" class="form-control" />
        <span asp-validation-for="CookingTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PreparationTime"></label>
        <input asp-for="PreparationTime" class="form-control" />
        <span asp-validation-for="PreparationTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PortionsCount"></label>
        <input asp-for="PortionsCount" class="form-control" />
        <span asp-validation-for="PortionsCount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId"></label>
        <select asp-for="CategoryId" class="form-control" asp-items="categoryItems"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Images"></label>
        <input asp-for="Images" class="form-control"/>
        <span asp-validation-for="Images" class="text-danger"></span>
    </div>
    <div id="IngredientsContainer">
        <label asp-for="Ingredients"></label>
        <a class="btn btn-success" onclick="AddMoreIngredients()">+</a>
    </div>
    <input type="submit" class="btn btn-primary" />
</form>

@section Scripts {
<script>
    var ingredientIndex = 0;
    function AddMoreIngredients() {
            $("#IngredientsContainer").append("<div class='form-control'> Name: <input type='text' name='Ingredients["+ ingredientIndex+ "].IngredientName' /> Quantity: <input type='text' name='Ingredients["+ ingredientIndex+ "].Quantity' /></div>");
        ingredientIndex++;
    }
</script>
}

Web/MoiteRecepti.Web/Views/Shared/_Layout.cshtml
@using MoiteRecepti.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
     @* <link rel="stylesheet" href="~/css/lazy.css"> 
 *@    <link rel="Stylesheet" href="~/css/style.css" /> 

</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg- border-bottom box-shadow mb-3">
            <div class="container">
                <div>
                    <a class="navbar-brand" href="#">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="~/images/[removal.ai]_fa2468b3-9f7e-42ab-8fd8-72dbffc34d1d-screenshot_5.png" width="200" height="100">
                            </a>
                    </a>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                    <ul class="navbar-nav flex-grow-1">
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="Create">Create Recipe</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="All">All Recipes</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="mt-auto">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/lib/popper/popper.min.js"></script>
    <script src="~/js/lazy.js"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/MoiteRecepti.Web/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) {
        <text>disabled</text>
} ">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 3; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 3; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) {
        <text>disabled</text>
}"><a class="page-link" asp-action="All" asp-route-id="@Model.NextPageNumber">Next</a></li>
    </ul>
</nav>